In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Seed_Data.csv')
df.head()

A      P       C     LK     WK  A_Coef    LKG  target
0  15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1  14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2  14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3  13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4  16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0

In [3]:
df = df[['A', 'LK']]
df.head()

A     LK
0  15.26  5.763
1  14.88  5.554
2  14.29  5.291
3  13.84  5.324
4  16.14  5.658

In [4]:
eigenvectors, eigenvalues, _ = np.linalg.svd(df.values, full_matrices=False)

In [5]:
eigenvalues

array([233.82000416,   9.26630575])

In [6]:
eigenvalues = np.cumsum(eigenvalues)
eigenvalues

array([233.82000416, 243.08630991])

In [7]:
eigenvalues /= eigenvalues.max()
eigenvalues

array([0.96188059, 1.        ])

In [8]:
eigenvectors

array([[-6.97617128e-02, -1.00859646e-02],
       [-6.79270734e-02, -3.20870088e-03],
       [-6.51700687e-02,  1.24688834e-03],
       [-6.34148645e-02, -1.89885943e-02],
       [-7.31338962e-02,  3.35798642e-02],
       [-6.56722944e-02, -4.98540353e-03],
       [-6.71786462e-02, -1.12534409e-02],
       [-6.46403020e-02, -1.85633793e-02],
       [-7.56863644e-02,  1.20143408e-02],
       [-7.46730662e-02,  2.19787654e-02],
       [-6.96887989e-02, -5.12838553e-03],
       [-6.43463206e-02, -2.33883894e-02],
       [-6.37864679e-02, -2.87463171e-02],
       [-6.34049360e-02, -3.69236261e-02],
       [-6.32490171e-02, -3.87290806e-02],
       [-6.64622241e-02,  6.44085331e-03],
       [-6.37112529e-02,  7.38453264e-03],
       [-7.11346535e-02,  2.99370951e-02],
       [-6.66860238e-02,  2.53427210e-02],
       [-5.87783107e-02, -5.11274572e-02],
       [-6.51949343e-02, -4.07656373e-02],
       [-6.47891060e-02, -2.86808875e-02],
       [-7.20318847e-02,  2.78643269e-02],
       [-5.

In [9]:
eigenvectors.shape

(210, 2)

In [10]:
P = eigenvectors[0]
P

array([-0.06976171, -0.01008596])