In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../Seed_Data.csv')
df.head()

A      P       C     LK     WK  A_Coef    LKG  target
0  15.26  14.84  0.8710  5.763  3.312   2.221  5.220       0
1  14.88  14.57  0.8811  5.554  3.333   1.018  4.956       0
2  14.29  14.09  0.9050  5.291  3.337   2.699  4.825       0
3  13.84  13.94  0.8955  5.324  3.379   2.259  4.805       0
4  16.14  14.99  0.9034  5.658  3.562   1.355  5.175       0

In [3]:
df = df[['A', 'LK']]
df.head()

A     LK
0  15.26  5.763
1  14.88  5.554
2  14.29  5.291
3  13.84  5.324
4  16.14  5.658

In [4]:
eigenvalues, eigenvectors = np.linalg.eig(np.cov(df.T))

In [5]:
eigenvalues

array([8.64390408, 0.01875194])

In [6]:
eigenvalues = np.cumsum(eigenvalues)
eigenvalues

array([8.64390408, 8.66265602])

In [7]:
eigenvalues /= eigenvalues.max()
eigenvalues

array([0.99783531, 1.        ])

In [8]:
eigenvectors

array([[ 0.98965371, -0.14347657],
       [ 0.14347657,  0.98965371]])

In [9]:
eigenvectors.shape

(2, 2)

In [10]:
P = eigenvectors[0]
P

array([ 0.98965371, -0.14347657])